### ISSUE TITLE
Duplcate key violation while create projections

### ISSUE THREAD

**Issue by adapik** [prooph/proophessor-do-symfony#17]
I've noticed several times "stream position" in table "projections" is less then expected (I've got unique constraint violation i my read table when event proceed twice).

To reproduce a bug I've added a simple console command 

https://github.com/Adapik/proophessor-do-symfony/commit/4dfe0be513f6c7f9c25607445bbc5d3a56c2f447

To run it just run `bin/console test:run`

It fills event store with events. Now when running `bin/console event-store:projection:run user_projection` or `bin/console event-store:projection:run todo_projection` I've got a DBAL Exception:

`
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'a82d2b4c-878f-4aaa-8827-03eed2fe56ae' for key 'PRIMARY'
`

It happens rather randomly in time, but in all cases in table  `projections` position counter is less then nr of event which has been created the last read model entry.

**Comment by adapik** [comment]
After a little debugging session I've found such behavior can be possible if sonething happened between read model persist and counter in table "projection" persisted, for instance killing projection script or db faluire.  It leads to inconsistency in data which can't be handled automatically.

https://github.com/prooph/pdo-event-store/blob/8780fd9431a539504583f569df2c359abcc413ff/src/Projection/PdoEventStoreReadModelProjector.php#L753

**Comment by prolic** [comment]
If you can't rely on that, use persist block size = 1

**Comment by adapik** [comment]
Unfortunately, It won't help. It decrease possible inconsistency to 1 event but not prevent it. The only way I see is to handle two persist (to read model table and to projections table) in db transaction. Probably I will have to use such approach.

But I suppose It's not a good idea, because the read model can be stored by another persistence mechanism (not even transactional).

**Comment by prolic** [comment]
In case you persist the read model and then kill the projector before it
can persist its state, yes. But there is nothing we can do about it. If
read model is mongodb and projector is postgres, then there is no common
transaction. You could add a table in the read model keeping track of all
handled event uuids, so you won't apply twice.
Generally I'd rather think of it as an edge case, and if you have this
problem regularly, you should find out who and why kills your projection
all the time.

**Comment by adapik** [comment]
@prolic Thank you for your answer! I agree that it should be handled on applicaion level. Finally the reason was not in that. But as I you advised I've found the original reason and here I'll try to describe.

As long as sequence modification in postgres is not transactional every rollback while persisting aggregate produces a "gap" in `no` column in Event Store table. Projectior counts its own position through increment "position" value. But events are loaded form event store by condition `no > :no`, where `:no` eventually is `$position + 1`. In case of "gap" in `no` it leads to divarication between event_store counter and projection counter.

I see two options to prevent this:
1) Somehow persist no of last event (do not calculate position)
2) load events with OFFSET (not an option due to performance)

**Comment by adapik** [comment]
Actually I made a fix for that, but It's not very clean + BC breaking. Used to change key() method in PdoStreamIterator:
https://github.com/Adapik/pdo-event-store/commit/ca2830c536aca4d73b28b1b44b0eac77d408f5fa

**Comment by prolic** [comment]
@Adapik The fix looks good to me. Wanna provide a PR and add a test-case?

**Comment by adapik** [comment]
Of course. I'll provide test case and PR later in prooph/pdo-event-store
