### ISSUE TITLE
Todo's with duplicate id possible?

### ISSUE THREAD

**Issue by milosa** [prooph/proophessor-do-symfony#22]
https://github.com/prooph/proophessor-do-symfony/blob/f9a6a5bf1642a291e01c26a58420ec0886b8c33b/src/ProophessorDo/Model/Todo/Handler/PostTodoHandler.php#L41-L52

Maybe I'm overlooking something, but shouldn't this also check to see whether a Todo with the TodoId in the Command already exists?

**Comment by UFOMelkor** [comment]
It is really unlikeley that two identical UUIDs are generated.

If this would happen anyway, it would hit a unique index in the database (e.g. event stream table definition of the [PostgresSingleStreamStrategy](https://github.com/prooph/pdo-event-store/blob/b89aad85b44b5c7bcb6134b3b0e700b88eaa0438/src/PersistenceStrategy/PostgresSingleStreamStrategy.php#L45)) and end in a [ConcurrenyException](https://github.com/prooph/pdo-event-store/blob/b89aad85b44b5c7bcb6134b3b0e700b88eaa0438/src/PostgresEventStore.php#L220).

**Comment by milosa** [comment]
I was more thinking about what would happen if a user sends a PostTodo API request twice.  (With the same ID)
Or what happens if a user tries to send a duplicate Id by manipulating the request.

But now I know that it is prevented by the unique index.
