### ISSUE TITLE
The latest mysql version 8 may cause issue

### ISSUE THREAD

**Issue by pchen014** [prooph/proophessor-do-symfony#26]
/var/www # bin/console event-store:event-stream:create

In AbstractMySQLDriver.php line 121:
  An exception occurred in driver: SQLSTATE[HY000] [2054] The server requeste  
  d authentication method unknown to the client

In PDOConnection.php line 47:   
  SQLSTATE[HY000] [2054] The server requested authentication method unknown t  
  o the client 

In PDOConnection.php line 43:
  SQLSTATE[HY000] [2054] The server requested authentication method unknown t  
  o the client

In PDOConnection.php line 43:
  PDO::__construct(): The server requested authentication method unknown to t  
  he client [caching_sha2_password]

-------------------------
Solution:
The docker composer by default using the latest mysql version which is 8 now. I specified version in docker-composer.yml and it worked.

  mysql:
    image: mysql:5

**Comment by prolic** [comment]
see https://github.com/prooph/proophessor-do-symfony/commit/cf0989f6016dfa5e7034e54bca6dec971bf145d5

fixed in master.

mysql is not supported by pdo-event-store. but I think there is a workaround for this issue.
