### ISSUE TITLE
Autdated docs and samples

### ISSUE THREAD

**Issue by BonBonSlick** [prooph/proophessor-do-symfony#31]
http://docs.getprooph.org/tutorial/event_sourcing_basics.html
and here you pass VO to event.
https://github.com/prooph/proophessor-do-symfony/blob/0d4140c6ac75943d5ff447dadc664b6a7300b4a1/src/ProophessorDo/Model/User/User.php

**Comment by prolic** [comment]
I don't know what you are looking for

**Comment by BonBonSlick** [comment]
@prolic
```
//Start new aggregate lifecycle by creating an "empty" instance
        $self = new self();

        //Record the very first domain event of the new aggregate
        //Note: we don't pass the value objects directly to the event but use their
        //primitive counterparts. This makes it much easier to work with the events later
        //and we don't need complex serializers when storing events.
        $self->recordThat(ShoppingSessionStarted::occur($basketId->toString(), [
            'shopping_session' => $shoppingSession->toString()
        ]));
```
```

    public static function registerWithData(
        UserId $userId,
        UserName $name,
        EmailAddress $emailAddress
    ): User {
        $self = new self();
        $self->recordThat(UserWasRegistered::withData($userId, $name, $emailAddress));
        return $self;
    }
```

And confusing
```

 $self->recordThat(UserWasRegistered::occur($entityId->value(), [
            'name' => userId,
          ....
        ]));
// or
        $self->recordThat(UserWasRegistered::withData($userId, $name,...));
```

**Comment by prolic** [comment]
occur:

https://github.com/prooph/event-sourcing/blob/master/src/AggregateChanged.php#L28-L30

withData:

something you implement yourself

**Comment by BonBonSlick** [comment]
@prolic  yeah. Maybe add in documentation the capability, difference and the best way to do it? Which way you would recommend and why?

**Comment by BonBonSlick** [comment]
@prolic  also noticed that 2 projects almost identical, to avoid double job and support of these two, maybe create only for symfony something specific? Like config files, yaml, xml, etc. 
https://github.com/prooph/proophessor-do-symfony/blob/master/src/ProophessorDo/Model/User/User.php
https://github.com/prooph/proophessor-do/blob/master/src/Model/User/User.php

**Comment by BonBonSlick** [comment]
@also, here in examples comparison goes with 
`get_class($this) === get_class($other)`
which indicates class A === class A
and in docs http://docs.getprooph.org/tutorial/event_sourcing_basics.html
```
 public function equals($other): bool
    {
        if(!$other instanceof self) {
            return false;
        }

        return $this->shoppingSession === $other->shoppingSession;
    }

```
which indicates 
class A == class A or  inherited from B or C 
 and other extended classes, will return true.
Example, I can compare UserId extends AbstracIt, in case UserId instance AbstractId returns true.

```
 $user = UserId::next();
     $user = UserId::next();
    $test = AbstractId::next();
        \dump($user instanceof  $test); // true
        die;
```
So the question why different approaches are used in samples and docs?

**Comment by BonBonSlick** [comment]
also, empty method https://github.com/prooph/proophessor-do/blob/master/src/Model/User/User.php#L90
and
https://github.com/prooph/proophessor-do-symfony/blob/master/src/ProophessorDo/Model/User/User.php#L90
because was copy pasted

**Comment by BonBonSlick** [comment]
I have created demo user class

`        $self->recordThat(UserCreated::withData($entityId));
`
says

```
Expected \Prooph\EventSourcing\AggregateChanged, got \App\Event\UserCreated 
Invocation parameter types are not compatible with declared.
```

while

```
use Prooph\EventSourcing\AggregateChanged;
final class UserCreated extends AggregateChanged
```

Why warning then?

**Comment by prolic** [comment]
This `Invocation parameter types are not compatible with declared.` is a PhpStorm warning only, right? If so, forget about this one.

Second, listen close, this is VERY IMPORTANT: You should NOT couple your domain model to any framework or library, including prooph/event-sourcing. Use it as a reference implementation to roll your own. You can also find this in the event sourcing docs: https://github.com/prooph/event-sourcing/blob/master/docs/repositories.md#event-sourced-aggregates

That's exactly the reason why prooph/event-sourcing gets completely deprecated next year. People ignore this very important fact and just install prooph/event-sourcing into their application.

Third: I'm sure there are things in the docs to improve, please don't expect anyone to improve the docs whenever someone finds something that may need improvement. We do this in our spare time. We do this for free. We are not paid doing all this. Please submit a PR for improvements and help us out. We can't do everything.

**Comment by BonBonSlick** [comment]
@prolic  ok, thanks

**Comment by BonBonSlick** [comment]
@prolic  can you tell me please what i am doing wrong

```
Cannot autowire service "App\EventStore\EventStoreUserCollection": argument "$eventStore" of method "__construct()" references interface "Prooph\EventStore\  
  EventStore" but no such service exists. Did you create a class that implements this interface?  
```


```
use Prooph\EventSourcing\Aggregate\AggregateRepository;
use Prooph\EventSourcing\Aggregate\AggregateType;
use Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator;
use Prooph\EventStore\EventStore;
use \Prooph\EventSourcing\Aggregate\Exception\InvalidArgumentException as AggregateInvalidArgumentException;

final class EventStoreUserCollection extends AggregateRepository implements UserCollection
{
    public function __construct(EventStore $eventStore)
    {
        //We inject a Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator that can handle our AggregateRoots
        parent::__construct(
            $eventStore,
            AggregateType::fromAggregateRootClass(User::class),
            new AggregateTranslator(),
            null, //We don't use a snapshot store in the example
            null, //Also a custom stream name is not required
            true //But we enable the "one-stream-per-aggregate" mode
        );
    }

    public function save(User $entity): void
    {
        \dump($entity);
        die;
        $this->saveAggregateRoot($entity);
    }
```

composer.json


```
    "prooph/event-sourcing": "^5.6",
    "prooph/event-store": "^7.3",
    "prooph/event-store-bus-bridge": "^3.2",
    "prooph/event-store-http-middleware": "^0.2.0",
    "prooph/event-store-symfony-bundle": "^0.5.0",
    "prooph/pdo-event-store": "^1.9",
```

tried this docs
http://docs.getprooph.org/event-sourcing/intro.html#4-1
and these sample
https://github.com/prooph/proophessor-do-symfony/blob/0d4140c6ac75943d5ff447dadc664b6a7300b4a1/src/ProophessorDo/Infrastructure/Repository/EventStoreUserCollection.php

I tried to do something like
```
 <service id="Prooph\EventStore\Pdo\PdoEventStore"
        alias="Prooph\EventStore\Pdo\PostgresEventStore" public="true" >
        </service>
```
But I thought package is already injected in service container.

bundles.php

`   
 Prooph\Bundle\EventStore\ProophEventStoreBundle::class => ['all' => true],
`
