### ISSUE TITLE
why so many problems

### ISSUE THREAD

**Issue by Veitor** [prooph/proophessor-do-symfony#35]
fisrt problem, i have fixed it by converting string to boolean tpye
![image](https://user-images.githubusercontent.com/7483890/48811596-809e3100-ed69-11e8-9c1c-0dd6e6cd833a.png)

second problem. why the option of swiftmailer is `url`? 
![image](https://user-images.githubusercontent.com/7483890/48811637-aa575800-ed69-11e8-809c-75911c2f4c7c.png)
![image](https://user-images.githubusercontent.com/7483890/48811649-b216fc80-ed69-11e8-9c0b-4b40bc1f0bff.png)

third problem. why can i not found `Symfony\Component\DependencyInjection`? which version should be installed?
![image](https://user-images.githubusercontent.com/7483890/48811744-1639c080-ed6a-11e8-87ec-94341749e1e9.png)

maybe there are many other problems will to be resolved. Do not you check this repo's correctness?

**Comment by codeliner** [comment]
Last PR changed [composer.lock](https://github.com/prooph/proophessor-do-symfony/pull/34/files#diff-1da2c7edc898c70e5a79a9997c98cecc)

Seems like some dependencies are broken now :( 

> Do not you check this repo's correctness?

I think last PR looked like a small change not related to functionality of the demo, so it wasn't checked. Thx for reporting. A PR that fixes the problems would be great!
