### ISSUE TITLE
Cannot autowire service "Prooph\ProophessorDo\Model\User\Service\ChecksUniqueUsersEmailAddress"

### ISSUE THREAD

**Issue by bassim** [prooph/proophessor-do-symfony#36]
(1/1) RuntimeException
Cannot autowire service "Prooph\ProophessorDo\Model\User\Service\ChecksUniqueUsersEmailAddress": argument "$userFinder" of method "Prooph\ProophessorDo\Infrastructure\Service\ChecksUniqueUsersEmailAddressFromReadModel::__construct()" references class "Prooph\ProophessorDo\Projection\User\UserFinder" but no such service exists. You should maybe alias this class to the existing "proophdo.todo_projection.user_finder" service.
--

**Comment by codeliner** [comment]
Can you provide a PR to fix the problem?

**Comment by dgreda** [comment]
I'm experiencing the same problem. Additionally I also had problem with swiftmailer, which I temporarily overcome by removing it from requirements, it was the following issue: ```Unrecognized option "url" under "swiftmailer.mailers.default"```
It somehow seems to me, as if the commited composer.lock is locked to versions of dependencies that your example app is not working with / is not compatible with.

**Comment by dave-redfern** [comment]
I believe the swiftmailer issue is due to the version in composer.json. For SF 4+ it should be >=3.1 to work properly; though it does appear that the composer.lock file is not consistent (e.g. installs old version of flex that is not compatible with changes in composer 1.7+). Changing swiftmailer-bundle to `"symfony/swiftmailer-bundle": "^3.1",` and then `composer update`, together with the corrections to the services.yaml suggested in PR #37 should get things working.

**Comment by codeliner** [comment]
Had to delete all dependencies and reinstall due to this exception:

```
[ErrorException]                                                                                                                                                                                           
  Declaration of Symfony\Flex\ParallelDownloader::getRemoteContents($originUrl, $fileUrl, $context) should be compatible with Composer\Util\RemoteFilesystem::getRemoteContents($originUrl, $fileUrl, $cont  
  ext, ?array &$responseHeaders = NULL) 
```

Dependency update can be found in #38 
@bassim @dave-redfern can you please verify that the problem is finally solved with the PR?

**Comment by dave-redfern** [comment]
@codeliner confirmed #38 fixes the dependencies.

I verified by: reverting any modified files, deleting var and vendor folders and then running `composer install`. It completed without errors.
